import * as $ from 'jquery'
import './blocks/_common/scss/main.scss'
import './blocks/like-button/like-button.js'
import './blocks/star-rating/star-rating.js'
import './blocks/star-rating/star-rating-floating.js'
import './blocks/range-slider/range-slider.js'
import './blocks/pagination/pagination.js'
import './blocks/dropdown/dropdown.js'
import './blocks/checkbox-list/checkbox-list.js'
import './blocks/dropdown-calendar/dropdown-calendar.js'
import './blocks/cards/booking-form/booking-form.js'
import './blocks/cards/room-preview/room-preview.js'
import './blocks/slick-carousel/slick-carousel.js'
import './blocks/menu/menu.js'
import './blocks/headersAndFooters/header/header.js'
import './blocks/headersAndFooters/footer/footer.js'
import './blocks/footer-menu/footer-menu.js'