import * as $ from 'jquery'
import './blocks/_common/scss/main.scss'
import './blocks/like-button/like-button.js'
import './blocks/star-rating/star-rating.js'
import './blocks/star-rating/star-rating-floating.js'
import './blocks/range-slider/range-slider.js'
import './blocks/pagination/pagination.js'
import './blocks/dropdown/dropdown.js'
import './blocks/checkbox-list/checkbox-list.js'
import './blocks/dropdown-calendar/dropdown-calendar.js'